### ISSUE TITLE
API Document not yet attached

### ISSUE THREAD

**Issue by rizkiramadhanx** [rizama/marketplace-api-search#1]
Mas boleh minta dokumentasi APInya (postman atau swagger) ?

**Comment by rizama** [comment]
Dokumentasi API udah ada swagger nya ya, setelah run apps di local bisa akses http://localhost:3000/api/

**Comment by rizkiramadhanx** [comment]
Terima kasih mas

**Comment by rizkiramadhanx** [comment]
sama cantumin env.example mas kalo bisa hihi 😁🙏

**Comment by rizama** [comment]
udah saya tambah juga ya mas, tp untuk shopee perlu maintenance lagi, nanti saya update ya mas :pray: :grin:

**Comment by rizkiramadhanx** [comment]
siap mas, lagi belajar2 aja sih ehehehe, smangat mas 😁
